server:
  port: 8083
  ssl:
    key-store: classpath:diogo_keystore.jks
    key-store-password: diogo123
    keyStoreType: JKS
    keyAlias: diogo
app:
  serverAddress: "https://localhost:8080"
  user: diogo
  password: diogo123
  cloudAddress: "https://localhost:8085"
  address: "https://localhost:8083"
trust-store: classpath:ServerTrustStore.jks
trust-store-password: server123